[book]
authors = ["Keep Zen"]
language = "zh-cn"
multilingual = true
src = "./"
title = "角落里的长生不老药"

[build]
#build-dir = "../book"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["theme/mermaid.min.js", "theme/mermaid-init.js"]
mathjax-support = true
