name: book
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jontze/action-mdbook@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          # Optional Plugins have to be enabled
          #use-linkcheck: true
          use-mermaid: true
      - name: mdbook build
        use: JamesIves/github-pages-deploy-action
        env: 
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          BRANCH: book
          BUILD_SCRIPT: mdbook build