name: book
on:
  push:
    branches:
      - main
jobs:
  release-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jontze/action-mdbook@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          # Optional Plugins have to be enabled
          #use-linkcheck: true
          use-mermaid: true
      - id: build
        name: mdbook build
        run: |
          mdbook build
          cd book
          git init
          git config user.name "GitHub"
          git config user.email "noreply@github.com"
          git add --all
          git commit --message "Auto deploy from GitHub Actions build $GITHUB_RUN_NUMBER"
          git remote add -t book git://github.com:KeepZen/the-corner-of-elixir.git
          git push --force book