name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Elixir action
        uses: mileschou/elixir-action@master
        with:
          args: mix docs
      - uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: book # The branch the action should deploy to.
          folder: doc # The folder the action should deploy.