name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: 1.13.4
          otp-version: 24
      - name: Install Dependence
        run: mix deps.get
      - name: Run mix docs
        run: mix docs
      - uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: book # The branch the action should deploy to.
          folder: doc # The folder the action should deploy.